# Generated by Django 3.2.6 on 2021-09-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('g1', models.CharField(max_length=100)),
                ('w1', models.CharField(max_length=100)),
                ('g2', models.CharField(max_length=100)),
                ('w2', models.CharField(max_length=100)),
            ],
        ),
    ]
