# Generated by Django 3.2.5 on 2021-09-23 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_answer_category_question_quizzes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='category',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quizzes',
        ),
    ]
